# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3557f01bc770fdd58db3ce9114180f6d60534c2405786eab4860b631ea43fc2d9d9d187a94c42dc2a7d8c236cfc2e94a6f28f2d263fb1481f26005c7e5f384a5

test:
  secret_key_base: c24a2af3b88010f4ebb2ed96aa722c396f3a579ed619d7bf84b5c8cb79cddcfb1b93fd4681966429160e693ba9111ef9a1b95b713cdab03ec35ed9894fd5b710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
